spring:
  application:
    name: FileUpload
  datasource:
    url: jdbc:h2:mem:h2
    username: admin
    password: admin
  jpa:
    openInView: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 1MB
      max-request-size: 2MB

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true